# Generated by Django 5.1 on 2024-12-02 20:04

import django.db.models.deletion
import reporter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idadministrador', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idempresa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('idsitio', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('CEP', models.CharField(max_length=8)),
                ('cidade', models.CharField(max_length=45)),
                ('endereco', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('idtecnico', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('idfoto', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('caminho', models.CharField(blank=True, editable=False, max_length=255)),
                ('nome', models.CharField(blank=True, max_length=45)),
                ('descricao', models.TextField()),
                ('metadados', models.JSONField(blank=True, editable=False, null=True)),
                ('idsitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.sitio')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateRelatorio',
            fields=[
                ('idtemplate_relatorio', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=45)),
                ('pedidos_fotos', models.JSONField(default=reporter.models.default_pedidos_fotos, help_text='Especifique as fotos que precisam ser solicitadas para este relatório em formato JSON.')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.administrador')),
                ('idempresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioFinal',
            fields=[
                ('idrelatorio_final', models.AutoField(primary_key=True, serialize=False)),
                ('endereco_server', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('data', models.DateField()),
                ('data_visita', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fotos', models.ManyToManyField(to='reporter.foto')),
                ('idsitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.sitio')),
                ('tecnico_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.tecnico')),
                ('idtemplate_relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.templaterelatorio')),
            ],
        ),
    ]
