# Generated by Django 5.1 on 2024-12-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriofinal',
            name='nome',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
