# Generated by Django 5.1 on 2024-12-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_relatoriofinal_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatoriofinal',
            name='data_visita',
        ),
    ]
