# Generated by Django 5.1 on 2024-12-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0003_remove_relatoriofinal_data_visita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriofinal',
            name='fotos',
            field=models.ManyToManyField(blank=True, to='reporter.foto'),
        ),
    ]
