# Generated by Django 5.1 on 2024-12-04 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0004_alter_relatoriofinal_fotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatoriofinal',
            name='updated_at',
        ),
    ]
