# Generated by Django 5.1 on 2024-12-04 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0005_remove_relatoriofinal_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatoriofinal',
            name='endereco_server',
        ),
    ]
