# Generated by Django 5.1 on 2024-12-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0006_remove_relatoriofinal_endereco_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriofinal',
            name='endereco_server',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
    ]
